### ISSUE TITLE
Game freeze

### ISSUE THREAD

**Issue by DyceIdo** [open-osrs/plugins#106]
2020-03-09 20:33:47 [Client] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.NoClassDefFoundError: net/runelite/api/events/PlayerDeath
	at bx.setCombatInfo(Actor.java:253)
	at bx.ap(Actor.java)
	at aq.l(AbstractWorldMapIcon.java:522)
	at am.d(class43.java:450)
	at cd.t(AttackOption.java:74)
	at client.hs(Client.java:6446)
	at client.fe(Client.java:2924)
	at client.ak(Client.java:1254)
	at bf.ax(GameShell.java:347)
	at bf.run(GameShell.java:326)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.runelite.api.events.PlayerDeath
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.net.URLClassLoader$1.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 11 common frames omitted
Caused by: java.util.zip.ZipException: ZipFile invalid LOC header (bad signature)
	at java.base/java.util.zip.ZipFile$ZipFileInputStream.initDataOffset(Unknown Source)
	at java.base/java.util.zip.ZipFile$ZipFileInputStream.read(Unknown Source)
	at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(Unknown Source)
	at java.base/java.util.zip.InflaterInputStream.read(Unknown Source)
	at java.base/java.util.jar.Manifest$FastInputStream.fill(Unknown Source)
	at java.base/java.util.jar.Manifest$FastInputStream.readLine(Unknown Source)
	at java.base/java.util.jar.Manifest$FastInputStream.readLine(Unknown Source)
	at java.base/java.util.jar.Attributes.read(Unknown Source)
	at java.base/java.util.jar.Manifest.read(Unknown Source)
	at java.base/java.util.jar.Manifest.<init>(Unknown Source)
	at java.base/java.util.jar.Manifest.<init>(Unknown Source)
	at java.base/java.util.jar.JarFile.getManifestFromReference(Unknown Source)
	at java.base/java.util.jar.JarFile.getManifest(Unknown Source)
	at java.base/jdk.internal.loader.URLClassPath$JarLoader$2.getManifest(Unknown Source)
	at java.base/java.net.URLClassLoader.defineClass(Unknown Source)
	... 17 common frames omitted

**Comment by xKylee** [comment]
Are you building the client yourself, and have you relaunched since Thursday?

**Comment by DyceIdo** [comment]
Not building myself, but I am using an external. Client(s) were launched today. 

Freezes tend to happen when adding friends/adding people to ignore/entering duels at duel arena.

**Comment by Ganom** [comment]
Are you running runelite as well as openosrs?

**Comment by DyceIdo** [comment]
Yes I am, however Kyle came down to the conclusion it was the external I was using.
