### ISSUE TITLE
Runecrafting plugin not tracking degradation of essence pouches.

### ISSUE THREAD

**Issue by Ajayrs123** [open-osrs/plugins#285]
2020-05-31 16:04:01 [AWT-EventQueue-0] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
2020-05-31 16:04:01 [AWT-EventQueue-0] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
2020-05-31 16:04:01 [AWT-EventQueue-0] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.3.1 in 'deployment' mode
2020-05-31 16:04:02 [AWT-EventQueue-0] ERROR o.p.update.DefaultUpdateRepository - https://github.com/Owain94/plugins.json
java.io.FileNotFoundException: https://github.com/Owain94/plugins.json
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at java.base/java.net.URL.openStream(Unknown Source)
	at org.pf4j.update.DefaultUpdateRepository.initPlugins(DefaultUpdateRepository.java:96)
	at org.pf4j.update.DefaultUpdateRepository.getPlugins(DefaultUpdateRepository.java:80)
	at org.pf4j.update.UpdateManager.getPluginsMap(UpdateManager.java:149)
	at org.pf4j.update.UpdateManager.getPlugins(UpdateManager.java:135)
	at net.runelite.client.plugins.ExternalPluginManager.testRepository(ExternalPluginManager.java:184)
	at net.runelite.client.plugins.openosrs.externals.ExternalPluginManagerPanel$2.mousePressed(ExternalPluginManagerPanel.java:191)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
2020-05-31 16:04:23 [AWT-EventQueue-0] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
2020-05-31 16:04:23 [AWT-EventQueue-0] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
2020-05-31 16:04:23 [AWT-EventQueue-0] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.3.1 in 'deployment' mode
2020-05-31 16:04:23 [AWT-EventQueue-0] ERROR o.p.update.DefaultUpdateRepository - https://raw.githubusercontent.com/https:/github.com/Owain94/OpenOSRS-RL-hub-hosting/Owain94/master/plugins.json
java.io.FileNotFoundException: https://raw.githubusercontent.com/https:/github.com/Owain94/OpenOSRS-RL-hub-hosting/Owain94/master/plugins.json
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
	at java.base/java.net.URL.openStream(Unknown Source)
	at org.pf4j.update.DefaultUpdateRepository.initPlugins(DefaultUpdateRepository.java:96)
	at org.pf4j.update.DefaultUpdateRepository.getPlugins(DefaultUpdateRepository.java:80)
	at org.pf4j.update.UpdateManager.getPluginsMap(UpdateManager.java:149)
	at org.pf4j.update.UpdateManager.getPlugins(UpdateManager.java:135)
	at net.runelite.client.plugins.ExternalPluginManager.testRepository(ExternalPluginManager.java:184)
	at net.runelite.client.plugins.ExternalPluginManager.testGHRepository(ExternalPluginManager.java:168)
	at net.runelite.client.plugins.openosrs.externals.ExternalPluginManagerPanel$1.mousePressed(ExternalPluginManagerPanel.java:119)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
2020-05-31 16:06:10 [AWT-EventQueue-0] INFO  org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
2020-05-31 16:06:10 [AWT-EventQueue-0] INFO  org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
2020-05-31 16:06:10 [AWT-EventQueue-0] INFO  org.pf4j.DefaultPluginManager - PF4J version 3.3.1 in 'deployment' mode
2020-05-31 16:06:35 [external-plugin-manager-0] INFO  n.r.c.plugins.ExternalPluginManager - Loading plugin AdvancedNotificationsPlugin
2020-05-31 16:06:35 [SwingWorker-pool-32-thread-1] INFO  n.r.c.plugins.ExternalPluginManager - External plugin instantiation took 38ms
2020-05-31 16:06:53 [external-plugin-manager-0] INFO  n.r.c.plugins.ExternalPluginManager - Loading plugin EssPouchPlugin
2020-05-31 16:06:53 [SwingWorker-pool-32-thread-2] INFO  n.r.c.plugins.ExternalPluginManager - External plugin instantiation took 9ms
2020-05-31 16:06:59 [external-plugin-manager-0] INFO  n.r.c.plugins.ExternalPluginManager - Loading plugin EssenceRunningPlugin
2020-05-31 16:06:59 [SwingWorker-pool-32-thread-3] INFO  n.r.c.plugins.ExternalPluginManager - External plugin instantiation took 25ms
2020-05-31 16:07:37 [external-plugin-manager-0] INFO  n.r.c.plugins.ExternalPluginManager - Loading plugin NPCOverheadDialoguePlugin
2020-05-31 16:07:37 [SwingWorker-pool-32-thread-4] INFO  n.r.c.plugins.ExternalPluginManager - External plugin instantiation took 9ms
2020-05-31 16:07:51 [external-plugin-manager-0] INFO  n.r.c.plugins.ExternalPluginManager - Loading plugin ProbabilityCalculatorPlugin
2020-05-31 16:07:51 [SwingWorker-pool-32-thread-5] INFO  n.r.c.plugins.ExternalPluginManager - External plugin instantiation took 14ms

**Comment by ngz03** [comment]
The counter doesn't seem to update properly unless the bank screen is open, or it has decayed completely and you get the dark mage to repair it.
