### ISSUE TITLE
Loot tracker issue

### ISSUE THREAD

**Issue by ElySkye** [open-osrs/plugins#555]
Hi there,

recently all of my previous loot from years collected have vanished. Even getting new loot, it doesnt save when client closed. Local record persistance and sync panel contents has never been unchecked. i have tried reinstalling and its still broken.

The log does its loaded : 2021-02-09 08:11:21 [scheduled-0] INFO  n.r.c.p.l.LootTrackerPlugin - Loaded 0 remote data entries
2021-02-09 08:11:47 [scheduled-0] INFO  n.r.c.p.l.LootTrackerPlugin - Loaded 70336 locally stored loot records

Heres one of my logs:
2021-02-09 09:52:35 [AWT-EventQueue-0] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.NullPointerException: null
	at net.runelite.client.plugins.loottracker.LootTrackerPanel.rebuild(LootTrackerPanel.java:615)
	at net.runelite.client.plugins.loottracker.LootTrackerPanel.addRecords(LootTrackerPanel.java:503)
	at net.runelite.client.plugins.loottracker.LootTrackerPlugin.lambda$startUp$1(LootTrackerPlugin.java:570)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

Have i done something wrong? the only thing i can think of is i turned on loot tracker for runelite, but ive also turned that off now and openosrs one is still broken and emptied.

**Comment by ElySkye** [comment]
[client_2021-02-09.0.log](https://github.com/open-osrs/plugins/files/5962510/client_2021-02-09.0.log)
whole log file if u need to look into it ^

**Comment by ElySkye** [comment]
Fixed it. for anyone wondering, it seems i deleted the stoned tracker plugin. reinstalled it and its back.
