### ISSUE TITLE
Tmorph borked

### ISSUE THREAD

**Issue by Crystalknoct** [open-osrs/plugins#60]
Due to a recent change tmorph doesnt seem to do anything I have a gif here showing all my side is good. https://i.imgur.com/nNglteB.gifv

1) Error injecting constructor, java.lang.IllegalArgumentException: head.png
  at net.runelite.client.plugins.tmorph.ui.TPanel.<init>(Unknown Source)
  while locating net.runelite.client.plugins.tmorph.ui.TPanel

1 error
	at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:441)
	at net.runelite.client.plugins.config.PluginListPanel.startPlugin(PluginListPanel.java:429)
	at net.runelite.client.plugins.config.PluginListItem.lambda$new$2(PluginListItem.java:154)
	at java.desktop/javax.swing.AbstractButton.fireItemStateChanged(AbstractButton.java:1995)
	at java.desktop/javax.swing.AbstractButton$Handler.itemStateChanged(AbstractButton.java:2315)
	at java.desktop/javax.swing.DefaultButtonModel.fireItemStateChanged(DefaultButtonModel.java:458)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setSelected(JToggleButton.java:364)
	at java.desktop/javax.swing.AbstractButton.setSelected(AbstractButton.java:341)
	at net.runelite.client.plugins.config.PluginListItem.setPluginEnabled(PluginListItem.java:201)
	at net.runelite.client.plugins.config.PluginListPanel.lambda$refresh$9(PluginListPanel.java:293)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at net.runelite.client.plugins.config.PluginListPanel.refresh(PluginListPanel.java:288)
	at net.runelite.client.plugins.config.PluginListPanel.rebuildPluginList(PluginListPanel.java:277)
	at net.runelite.client.plugins.config.ConfigPlugin.startUp(ConfigPlugin.java:95)
	at net.runelite.client.plugins.PluginManager.startPlugin(PluginManager.java:419)
	at net.runelite.client.plugins.PluginManager.lambda$startPlugins$2(PluginManager.java:260)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: com.google.inject.ProvisionException: Unable to provision, see the following errors:

**Comment by xKylee** [comment]
resolved.
