### ISSUE TITLE
npchighlight: npe

### ISSUE THREAD

**Issue by SRLJustin** [open-osrs/plugins#96]
```java
2020-02-29 23:29:15 [Client] WARN  n.r.c.ui.overlay.OverlayRenderer - Error during overlay rendering
java.lang.NullPointerException: null
	at java.desktop/sun.java2d.marlin.DMarlinRenderingEngine.strokeTo(Unknown Source)
	at java.desktop/sun.java2d.marlin.DMarlinRenderingEngine.strokeTo(Unknown Source)
	at java.desktop/sun.java2d.marlin.DMarlinRenderingEngine.getAATileGenerator(Unknown Source)
	at java.desktop/sun.java2d.pipe.AAShapePipe.renderPath(Unknown Source)
	at java.desktop/sun.java2d.pipe.AAShapePipe.draw(Unknown Source)
	at java.desktop/sun.java2d.pipe.PixelToParallelogramConverter.draw(Unknown Source)
	at java.desktop/sun.java2d.pipe.ValidatePipe.draw(Unknown Source)
	at java.desktop/sun.java2d.SunGraphics2D.draw(Unknown Source)
	at net.runelite.client.plugins.npchighlight.NpcSceneOverlay.renderNpcOverlay(NpcSceneOverlay.java:196)
	at net.runelite.client.plugins.npchighlight.NpcSceneOverlay.render(NpcSceneOverlay.java:85)
	at net.runelite.client.ui.overlay.OverlayRenderer.safeRender(OverlayRenderer.java:510)
	at net.runelite.client.ui.overlay.OverlayRenderer.render(OverlayRenderer.java:254)
	at net.runelite.client.callback.Hooks.drawScene(Hooks.java:424)
	at em.at(Scene.java:315)
	at aa.gq(WorldMapSection1.java:4455)
	at ig.iy(FloorOverlayDefinition.java:9106)
	at gb.io(ServerPacket.java:8995)
	at client.gp(Client.java:4179)
	at client.ac(Client.java:1282)
	at bf.aj(GameShell.java:373)
	at bf.run(GameShell.java:327)
	at java.base/java.lang.Thread.run(Unknown Source)
```

npcs to highlight: Phials,Baby impling, Young impling, Gourmet impling, Earth impling, Essence impling,

**Comment by xKylee** [comment]
im pretty sure, this has been fixed. if it reoccurs, please reopen this ticket.
